apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim-2
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi